export { createApiClient } from './client'
export type { ApiClient, TokenGetter } from './client'

export { createAuthApi } from './auth'
export { createMeetingsApi } from './meetings'
export { createTasksApi } from './tasks'
export { createProjectsApi } from './projects'
export { createAnalysisApi } from './analysis'
export { createCalendarApi } from './calendar'
export type { CalendarEvent } from './calendar'
export { createTranslateApi } from './translate'
export { createMemoryApi } from './memory'
export type { Memory } from './memory'
export { createMindmapApi } from './mindmap'
export { createRecordingsApi } from './recordings'
export type { ImportRecordingResponse } from './recordings'
export type { SlidesStatus } from './analysis'

export { createAgentsApi } from './agents'
export { createChatsApi } from './chats'
export { createAssistantApi } from './assistant'
export { createIntegrationsApi } from './integrations'
export { createCalendarFeedApi } from './calendar-feed'
export { createPreferencesApi } from './preferences'
